name: markuplint-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/markuplint/markuplint.config.js'
      - 'packages/markuplint/package.json'
      - 'packages/markuplint/__tests__/valid/**/*.html'
  push:
    branches:
      - main
    paths:
      - 'packages/markuplint/markuplint.config.js'
      - 'packages/markuplint/package.json'
      - 'packages/markuplint/__tests__/valid/**/*.html'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm test -w '@w0s/markuplint-config'
