name: ts-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/tsconfig/tsconfig.json'
      - 'packages/tsconfig/package.json'
      - 'packages/tsconfig/__tests__/@types/*.d.ts'
      - 'packages/tsconfig/__tests__/valid/**/*.ts'
      - 'packages/tsconfig/__tests__/tsconfig-valid.json'
  push:
    branches:
      - main
    paths:
      - 'packages/tsconfig/tsconfig.json'
      - 'packages/tsconfig/package.json'
      - 'packages/tsconfig/__tests__/@types/*.d.ts'
      - 'packages/tsconfig/__tests__/valid/**/*.ts'
      - 'packages/tsconfig/__tests__/tsconfig-valid.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test -w '@w0s/tsconfig'
